version: '3.1'
services:
  mysql:
    image: daocloud.io/library/mysql:5.7.4
    container_name: mysql5.7.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - ~/Docker/mysql5.7.4/data:/var/lib/mysql
  php7.0.5:
    build: ./images/php7.0.5
    container_name: php7.0.5
    links:
      - nginx:pms.test
      - nginx:www.spm.test
      - nginx:ifs.test
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ~/Code/php:/var/www
      - ~/Code/config:/data/www/apollo-config
      - ./conf/php7.0.5/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  php5.6.22:
    build: ./images/php5.6.22
    container_name: php5.6.22
    links:
      - nginx:pms.test
      - nginx:www.spm.test
      - nginx:ifs.test
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ~/Code/php:/var/www
      - ~/Code/config:/data/www/apollo-config
      - ./conf/php5.6.22/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/nginx/site/:/etc/nginx/conf.d/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/Code/php:/var/www
      - ~/Code/config:/data/www/apollo-config
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    links:
      - nginx:pkg.august.test
    hostname: pkg.august.test
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://pkg.august.test'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
  gitlab-runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    links:
      - nginx:pkg.august.test
    volumes:
      - ~/.netrc:/root/.netrc
      - ~/.netrc:/home/gitlab-runner/.netrc
      - '$GITLAB_HOME/runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'

